//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.Position))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.Desk))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.JobStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.TypeDishes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.Menuu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.DeskMenu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RestaurantManagement.ServiceReference1.Worker))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Position : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Desk", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Desk : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.JobStatus JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumDesk1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.JobStatus Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDesk1 {
            get {
                return this.NumDesk1Field;
            }
            set {
                if ((this.NumDesk1Field.Equals(value) != true)) {
                    this.NumDesk1Field = value;
                    this.RaisePropertyChanged("NumDesk1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class JobStatus : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Windows.Media.Color ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Situation1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Windows.Media.Color Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situation1 {
            get {
                return this.Situation1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Situation1Field, value) != true)) {
                    this.Situation1Field = value;
                    this.RaisePropertyChanged("Situation1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeDishes", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class TypeDishes : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ty {
            get {
                return this.TyField;
            }
            set {
                if ((object.ReferenceEquals(this.TyField, value) != true)) {
                    this.TyField = value;
                    this.RaisePropertyChanged("Ty");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menuu", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Menuu : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GlutenFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pic1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.TypeDishes TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GlutenFree {
            get {
                return this.GlutenFreeField;
            }
            set {
                if ((this.GlutenFreeField.Equals(value) != true)) {
                    this.GlutenFreeField = value;
                    this.RaisePropertyChanged("GlutenFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information {
            get {
                return this.InformationField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationField, value) != true)) {
                    this.InformationField = value;
                    this.RaisePropertyChanged("Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pic1 {
            get {
                return this.Pic1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pic1Field, value) != true)) {
                    this.Pic1Field = value;
                    this.RaisePropertyChanged("Pic1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.TypeDishes Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeskMenu", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class DeskMenu : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.Desk DeskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.Menuu MenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.JS StatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.Desk Desk {
            get {
                return this.DeskField;
            }
            set {
                if ((object.ReferenceEquals(this.DeskField, value) != true)) {
                    this.DeskField = value;
                    this.RaisePropertyChanged("Desk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.Menuu Menu {
            get {
                return this.MenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuField, value) != true)) {
                    this.MenuField = value;
                    this.RaisePropertyChanged("Menu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.JS Stat {
            get {
                return this.StatField;
            }
            set {
                if ((this.StatField.Equals(value) != true)) {
                    this.StatField = value;
                    this.RaisePropertyChanged("Stat");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Worker : RestaurantManagement.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Gender1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Password1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RestaurantManagement.ServiceReference1.Position PosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserName1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender1 {
            get {
                return this.Gender1Field;
            }
            set {
                if ((this.Gender1Field.Equals(value) != true)) {
                    this.Gender1Field = value;
                    this.RaisePropertyChanged("Gender1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password1 {
            get {
                return this.Password1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Password1Field, value) != true)) {
                    this.Password1Field = value;
                    this.RaisePropertyChanged("Password1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RestaurantManagement.ServiceReference1.Position Pos {
            get {
                return this.PosField;
            }
            set {
                if ((object.ReferenceEquals(this.PosField, value) != true)) {
                    this.PosField = value;
                    this.RaisePropertyChanged("Pos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName1 {
            get {
                return this.UserName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserName1Field, value) != true)) {
                    this.UserName1Field = value;
                    this.RaisePropertyChanged("UserName1");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JS", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum JS : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        פנוי = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        מלצר = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        טבח = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        מוכן = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        תפוס = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WorkerList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Worker")]
    [System.SerializableAttribute()]
    public class WorkerList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.Worker> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DeskList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Desk")]
    [System.SerializableAttribute()]
    public class DeskList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.Desk> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PositionList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Position")]
    [System.SerializableAttribute()]
    public class PositionList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.Position> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TypeDishesList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="TypeDishes")]
    [System.SerializableAttribute()]
    public class TypeDishesList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.TypeDishes> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="JobStatusList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="JobStatus")]
    [System.SerializableAttribute()]
    public class JobStatusList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.JobStatus> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MenuList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Menuu")]
    [System.SerializableAttribute()]
    public class MenuList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.Menuu> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DeskMenuList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="DeskMenu")]
    [System.SerializableAttribute()]
    public class DeskMenuList : System.Collections.Generic.List<RestaurantManagement.ServiceReference1.DeskMenu> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginWorker", ReplyAction="http://tempuri.org/IService1/LoginWorkerResponse")]
        RestaurantManagement.ServiceReference1.Worker LoginWorker(string uname, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginWorker", ReplyAction="http://tempuri.org/IService1/LoginWorkerResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.Worker> LoginWorkerAsync(string uname, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        RestaurantManagement.ServiceReference1.WorkerList GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.WorkerList> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDesks", ReplyAction="http://tempuri.org/IService1/GetAllDesksResponse")]
        RestaurantManagement.ServiceReference1.DeskList GetAllDesks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDesks", ReplyAction="http://tempuri.org/IService1/GetAllDesksResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskList> GetAllDesksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPosition", ReplyAction="http://tempuri.org/IService1/GetPositionResponse")]
        RestaurantManagement.ServiceReference1.PositionList GetPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPosition", ReplyAction="http://tempuri.org/IService1/GetPositionResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.PositionList> GetPositionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDish", ReplyAction="http://tempuri.org/IService1/GetDishResponse")]
        RestaurantManagement.ServiceReference1.TypeDishesList GetDish();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDish", ReplyAction="http://tempuri.org/IService1/GetDishResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.TypeDishesList> GetDishAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobs", ReplyAction="http://tempuri.org/IService1/GetJobsResponse")]
        RestaurantManagement.ServiceReference1.JobStatusList GetJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobs", ReplyAction="http://tempuri.org/IService1/GetJobsResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.JobStatusList> GetJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDishes", ReplyAction="http://tempuri.org/IService1/GetAllDishesResponse")]
        RestaurantManagement.ServiceReference1.MenuList GetAllDishes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDishes", ReplyAction="http://tempuri.org/IService1/GetAllDishesResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.MenuList> GetAllDishesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertWorker", ReplyAction="http://tempuri.org/IService1/InsertWorkerResponse")]
        int InsertWorker(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertWorker", ReplyAction="http://tempuri.org/IService1/InsertWorkerResponse")]
        System.Threading.Tasks.Task<int> InsertWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateWorker", ReplyAction="http://tempuri.org/IService1/UpdateWorkerResponse")]
        int UpdateWorker(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateWorker", ReplyAction="http://tempuri.org/IService1/UpdateWorkerResponse")]
        System.Threading.Tasks.Task<int> UpdateWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteWorker", ReplyAction="http://tempuri.org/IService1/DeleteWorkerResponse")]
        int DeleteWorker(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteWorker", ReplyAction="http://tempuri.org/IService1/DeleteWorkerResponse")]
        System.Threading.Tasks.Task<int> DeleteWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDish", ReplyAction="http://tempuri.org/IService1/InsertDishResponse")]
        int InsertDish(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDish", ReplyAction="http://tempuri.org/IService1/InsertDishResponse")]
        System.Threading.Tasks.Task<int> InsertDishAsync(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDish", ReplyAction="http://tempuri.org/IService1/UpdateDishResponse")]
        int UpdateDish(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDish", ReplyAction="http://tempuri.org/IService1/UpdateDishResponse")]
        System.Threading.Tasks.Task<int> UpdateDishAsync(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDish", ReplyAction="http://tempuri.org/IService1/DeleteDishResponse")]
        int DeleteDish(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDish", ReplyAction="http://tempuri.org/IService1/DeleteDishResponse")]
        System.Threading.Tasks.Task<int> DeleteDishAsync(RestaurantManagement.ServiceReference1.Menuu dish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WaitingWaiter", ReplyAction="http://tempuri.org/IService1/WaitingWaiterResponse")]
        void WaitingWaiter(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WaitingWaiter", ReplyAction="http://tempuri.org/IService1/WaitingWaiterResponse")]
        System.Threading.Tasks.Task WaitingWaiterAsync(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        byte[] GetImage(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        void SaveImage(byte[] imageArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeskStatus", ReplyAction="http://tempuri.org/IService1/DeskStatusResponse")]
        void DeskStatus(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeskStatus", ReplyAction="http://tempuri.org/IService1/DeskStatusResponse")]
        System.Threading.Tasks.Task DeskStatusAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFreeDesk", ReplyAction="http://tempuri.org/IService1/GetFreeDeskResponse")]
        RestaurantManagement.ServiceReference1.Desk GetFreeDesk(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFreeDesk", ReplyAction="http://tempuri.org/IService1/GetFreeDeskResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.Desk> GetFreeDeskAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeDeskStatus", ReplyAction="http://tempuri.org/IService1/ChangeDeskStatusResponse")]
        void ChangeDeskStatus(RestaurantManagement.ServiceReference1.Desk desk, RestaurantManagement.ServiceReference1.JS status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeDeskStatus", ReplyAction="http://tempuri.org/IService1/ChangeDeskStatusResponse")]
        System.Threading.Tasks.Task ChangeDeskStatusAsync(RestaurantManagement.ServiceReference1.Desk desk, RestaurantManagement.ServiceReference1.JS status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBill", ReplyAction="http://tempuri.org/IService1/GetBillResponse")]
        double GetBill(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBill", ReplyAction="http://tempuri.org/IService1/GetBillResponse")]
        System.Threading.Tasks.Task<double> GetBillAsync(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDishToDesk", ReplyAction="http://tempuri.org/IService1/AddDishToDeskResponse")]
        void AddDishToDesk(RestaurantManagement.ServiceReference1.Menuu menu, RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDishToDesk", ReplyAction="http://tempuri.org/IService1/AddDishToDeskResponse")]
        System.Threading.Tasks.Task AddDishToDeskAsync(RestaurantManagement.ServiceReference1.Menuu menu, RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeskList", ReplyAction="http://tempuri.org/IService1/GetDeskListResponse")]
        RestaurantManagement.ServiceReference1.DeskMenuList GetDeskList(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeskList", ReplyAction="http://tempuri.org/IService1/GetDeskListResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskMenuList> GetDeskListAsync(RestaurantManagement.ServiceReference1.Desk desk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ss", ReplyAction="http://tempuri.org/IService1/ssResponse")]
        void ss(RestaurantManagement.ServiceReference1.DeskMenuList dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ss", ReplyAction="http://tempuri.org/IService1/ssResponse")]
        System.Threading.Tasks.Task ssAsync(RestaurantManagement.ServiceReference1.DeskMenuList dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeskOrder", ReplyAction="http://tempuri.org/IService1/DeskOrderResponse")]
        double DeskOrder(RestaurantManagement.ServiceReference1.DeskMenuList list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeskOrder", ReplyAction="http://tempuri.org/IService1/DeskOrderResponse")]
        System.Threading.Tasks.Task<double> DeskOrderAsync(RestaurantManagement.ServiceReference1.DeskMenuList list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeskMenuList", ReplyAction="http://tempuri.org/IService1/GetDeskMenuListResponse")]
        RestaurantManagement.ServiceReference1.DeskMenuList GetDeskMenuList(RestaurantManagement.ServiceReference1.JS js);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDeskMenuList", ReplyAction="http://tempuri.org/IService1/GetDeskMenuListResponse")]
        System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskMenuList> GetDeskMenuListAsync(RestaurantManagement.ServiceReference1.JS js);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeStatus", ReplyAction="http://tempuri.org/IService1/ChangeStatusResponse")]
        int ChangeStatus(RestaurantManagement.ServiceReference1.DeskMenu deskMenu, RestaurantManagement.ServiceReference1.JS js);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeStatus", ReplyAction="http://tempuri.org/IService1/ChangeStatusResponse")]
        System.Threading.Tasks.Task<int> ChangeStatusAsync(RestaurantManagement.ServiceReference1.DeskMenu deskMenu, RestaurantManagement.ServiceReference1.JS js);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RestaurantManagement.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RestaurantManagement.ServiceReference1.IService1>, RestaurantManagement.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RestaurantManagement.ServiceReference1.Worker LoginWorker(string uname, string pass) {
            return base.Channel.LoginWorker(uname, pass);
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.Worker> LoginWorkerAsync(string uname, string pass) {
            return base.Channel.LoginWorkerAsync(uname, pass);
        }
        
        public RestaurantManagement.ServiceReference1.WorkerList GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.WorkerList> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public RestaurantManagement.ServiceReference1.DeskList GetAllDesks() {
            return base.Channel.GetAllDesks();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskList> GetAllDesksAsync() {
            return base.Channel.GetAllDesksAsync();
        }
        
        public RestaurantManagement.ServiceReference1.PositionList GetPosition() {
            return base.Channel.GetPosition();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.PositionList> GetPositionAsync() {
            return base.Channel.GetPositionAsync();
        }
        
        public RestaurantManagement.ServiceReference1.TypeDishesList GetDish() {
            return base.Channel.GetDish();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.TypeDishesList> GetDishAsync() {
            return base.Channel.GetDishAsync();
        }
        
        public RestaurantManagement.ServiceReference1.JobStatusList GetJobs() {
            return base.Channel.GetJobs();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.JobStatusList> GetJobsAsync() {
            return base.Channel.GetJobsAsync();
        }
        
        public RestaurantManagement.ServiceReference1.MenuList GetAllDishes() {
            return base.Channel.GetAllDishes();
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.MenuList> GetAllDishesAsync() {
            return base.Channel.GetAllDishesAsync();
        }
        
        public int InsertWorker(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.InsertWorker(worker);
        }
        
        public System.Threading.Tasks.Task<int> InsertWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.InsertWorkerAsync(worker);
        }
        
        public int UpdateWorker(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.UpdateWorker(worker);
        }
        
        public System.Threading.Tasks.Task<int> UpdateWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.UpdateWorkerAsync(worker);
        }
        
        public int DeleteWorker(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.DeleteWorker(worker);
        }
        
        public System.Threading.Tasks.Task<int> DeleteWorkerAsync(RestaurantManagement.ServiceReference1.Worker worker) {
            return base.Channel.DeleteWorkerAsync(worker);
        }
        
        public int InsertDish(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.InsertDish(dish);
        }
        
        public System.Threading.Tasks.Task<int> InsertDishAsync(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.InsertDishAsync(dish);
        }
        
        public int UpdateDish(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.UpdateDish(dish);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDishAsync(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.UpdateDishAsync(dish);
        }
        
        public int DeleteDish(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.DeleteDish(dish);
        }
        
        public System.Threading.Tasks.Task<int> DeleteDishAsync(RestaurantManagement.ServiceReference1.Menuu dish) {
            return base.Channel.DeleteDishAsync(dish);
        }
        
        public void WaitingWaiter(RestaurantManagement.ServiceReference1.Desk desk) {
            base.Channel.WaitingWaiter(desk);
        }
        
        public System.Threading.Tasks.Task WaitingWaiterAsync(RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.WaitingWaiterAsync(desk);
        }
        
        public byte[] GetImage(string fileName) {
            return base.Channel.GetImage(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
        
        public void SaveImage(byte[] imageArray, string fileName) {
            base.Channel.SaveImage(imageArray, fileName);
        }
        
        public System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string fileName) {
            return base.Channel.SaveImageAsync(imageArray, fileName);
        }
        
        public void DeskStatus(int n) {
            base.Channel.DeskStatus(n);
        }
        
        public System.Threading.Tasks.Task DeskStatusAsync(int n) {
            return base.Channel.DeskStatusAsync(n);
        }
        
        public RestaurantManagement.ServiceReference1.Desk GetFreeDesk(int n) {
            return base.Channel.GetFreeDesk(n);
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.Desk> GetFreeDeskAsync(int n) {
            return base.Channel.GetFreeDeskAsync(n);
        }
        
        public void ChangeDeskStatus(RestaurantManagement.ServiceReference1.Desk desk, RestaurantManagement.ServiceReference1.JS status) {
            base.Channel.ChangeDeskStatus(desk, status);
        }
        
        public System.Threading.Tasks.Task ChangeDeskStatusAsync(RestaurantManagement.ServiceReference1.Desk desk, RestaurantManagement.ServiceReference1.JS status) {
            return base.Channel.ChangeDeskStatusAsync(desk, status);
        }
        
        public double GetBill(RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.GetBill(desk);
        }
        
        public System.Threading.Tasks.Task<double> GetBillAsync(RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.GetBillAsync(desk);
        }
        
        public void AddDishToDesk(RestaurantManagement.ServiceReference1.Menuu menu, RestaurantManagement.ServiceReference1.Desk desk) {
            base.Channel.AddDishToDesk(menu, desk);
        }
        
        public System.Threading.Tasks.Task AddDishToDeskAsync(RestaurantManagement.ServiceReference1.Menuu menu, RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.AddDishToDeskAsync(menu, desk);
        }
        
        public RestaurantManagement.ServiceReference1.DeskMenuList GetDeskList(RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.GetDeskList(desk);
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskMenuList> GetDeskListAsync(RestaurantManagement.ServiceReference1.Desk desk) {
            return base.Channel.GetDeskListAsync(desk);
        }
        
        public void ss(RestaurantManagement.ServiceReference1.DeskMenuList dd) {
            base.Channel.ss(dd);
        }
        
        public System.Threading.Tasks.Task ssAsync(RestaurantManagement.ServiceReference1.DeskMenuList dd) {
            return base.Channel.ssAsync(dd);
        }
        
        public double DeskOrder(RestaurantManagement.ServiceReference1.DeskMenuList list) {
            return base.Channel.DeskOrder(list);
        }
        
        public System.Threading.Tasks.Task<double> DeskOrderAsync(RestaurantManagement.ServiceReference1.DeskMenuList list) {
            return base.Channel.DeskOrderAsync(list);
        }
        
        public RestaurantManagement.ServiceReference1.DeskMenuList GetDeskMenuList(RestaurantManagement.ServiceReference1.JS js) {
            return base.Channel.GetDeskMenuList(js);
        }
        
        public System.Threading.Tasks.Task<RestaurantManagement.ServiceReference1.DeskMenuList> GetDeskMenuListAsync(RestaurantManagement.ServiceReference1.JS js) {
            return base.Channel.GetDeskMenuListAsync(js);
        }
        
        public int ChangeStatus(RestaurantManagement.ServiceReference1.DeskMenu deskMenu, RestaurantManagement.ServiceReference1.JS js) {
            return base.Channel.ChangeStatus(deskMenu, js);
        }
        
        public System.Threading.Tasks.Task<int> ChangeStatusAsync(RestaurantManagement.ServiceReference1.DeskMenu deskMenu, RestaurantManagement.ServiceReference1.JS js) {
            return base.Channel.ChangeStatusAsync(deskMenu, js);
        }
    }
}
